### ISSUE TITLE
Float:left/margins

### ISSUE THREAD

**Issue by trebird** [trebird/sections#2]
Hello @thomasjbradley

Just giving sections another go, and having trouble with the sizing/positioning of things. Not sure where/how to fix it to make my site match the screenshots. 

Thank you!

**Comment by thomasjbradley** [comment]
Don’t use `float`—you’ll never be able to center anything.
Also remove the `align-content` property.

Add a `<div>` around the `<img>` and use that for positioning; the only properties that should be on `img` are `width` & `display: block`.

Try to use `padding` only on the `<div>` tags instead of `margin`. Remember that `margin` takes up space outside the boxes so it’s going to force them to break lines more quickly than padding.
